### ISSUE TITLE
Steps not defined

### ISSUE THREAD

**Issue by Renari** [semantic-release/exec#111]
I'm trying to use exec to bake the version number into my application before build.

package.json
```
  "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/github",
        {
          "assets": [
            {
              "path": "build/release.tar.gz"
            }
          ]
        }
      ],
      [
        "@semantic-release/exec",
        {
          "prepareCmd": "sed -i 's/<version>/${steps.semantic.outputs.new_release_version}/' src/index.ts && npm run build && cd build && tar -czf release.tar.gz **/* ../package.json ../package-lock.json"
        }
      ]
    ]
  }
```

I've defined these plugins in `package.json` to do so, however when trying to execute a build using this procedure the build crashes saying `steps` is not defined in exec.

```
[4:16:14 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/exec"
[4:16:14 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/exec"
[4:16:14 PM] [semantic-release] › ✖  An error occurred while running semantic-release: ReferenceError: steps is not defined
    at eval (lodash.templateSources[0]:9:10)
    at module.exports (/home/runner/work/Shubot/Shubot/node_modules/@semantic-release/exec/lib/exec.js:7:39)
    at prepare (/home/runner/work/Shubot/Shubot/node_modules/@semantic-release/exec/index.js:54:11)
    at validator (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/p-reduce/index.js:17:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  pluginName: '@semantic-release/exec'
}
##[error]ReferenceError: steps is not defined
```

**Comment by Renari** [comment]
This was because of this: `steps.semantic.outputs.new_release_version` using `nextRelease.version` instead fixed the issue.
